name: CI

on:
  push:
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13, macos-latest]
        include:
          - os: windows-latest
            build: bilibili-senior-Windows.exe
          - os: ubuntu-latest
            build: bilibili-senior-Linux
          - os: macos-13
            build: bilibili-senior-macOS-Intel
          - os: macos-latest
            build: bilibili-senior-macOS-Apple_Silicon
    runs-on: ${{ matrix.os }}
    env:
      version: ${{ github.ref_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Binary
        run: pyinstaller senior.spec

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: dist/*
          name: ${{ github.ref_name }}-${{ matrix.build }}

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/${{ github.ref_name }}-${{ matrix.build }}
